apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: "auth-service|ticket-service|analytics-service|notification-service|ai-brain|voice-agent|voice-agent-api|whatsapp-service|dashboard"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
